# Generated by Django 3.2 on 2021-05-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('telephone_contact', models.CharField(max_length=100)),
                ('department_to_vist', models.CharField(choices=[('Testing', 'Testing'), ('Certification', 'Certification'), ('Imports Inspection', 'Imports Inspection'), ('UNBS Market Surveillance', 'UNBS Market Surveillance'), ('Finance & Administration', 'Finance & Administration'), ('Human Resource', 'Human Resource'), ('Office of the Executive Director', 'Office of the Executive Director')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('first_time_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('were_you_served', models.BooleanField(default=False)),
                ('reason_or_feedback', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
