# Generated by Django 3.2 on 2021-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='department_to_vist',
            field=models.CharField(choices=[('Testing', 'Testing'), ('Certification', 'Certification'), ('Imports Inspection', 'Imports Inspection'), ('UNBS Market Surveillance', 'UNBS Market Surveillance'), ('Finance & Administration', 'Finance & Administration'), ('Human Resource', 'Human Resource'), ('Office of the Executive Director', 'Office of the Executive Director')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_time_customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
