# Generated by Django 3.2 on 2021-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210503_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='provided_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
